ALTER TABLE POSCLIENT ADD IF NOT EXISTS logincode varchar(64) NOT NULL DEFAULT '';

ALTER TABLE POSCLIENT DROP CONSTRAINT IF EXISTS C_POSCLIENT_UNIQUE_LOGINCODE;
ALTER TABLE POSCLIENT ADD CONSTRAINT C_POSCLIENT_UNIQUE_LOGINCODE UNIQUE(logincode);

CREATE TABLE IF NOT EXISTS MLUSER(
    id SERIAL PRIMARY KEY,
    username varchar(100),
    hashed_password varchar(1000),
    email varchar(200),
    image varchar(500) DEFAULT '',
    date_inserted timestamp DEFAULT CURRENT_TIMESTAMP,
    date_updated timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER t_MLUSER_UPDATE BEFORE UPDATE ON MLUSER FOR EACH ROW EXECUTE PROCEDURE fn_update_date_updated();

ALTER TABLE MLUSER DROP CONSTRAINT IF EXISTS C_MLUSER_UNIQUE_USERNAME;
ALTER TABLE MLUSER ADD CONSTRAINT C_MLUSER_UNIQUE_USERNAME UNIQUE(username);

ALTER TABLE PRODUCT ADD IF NOT EXISTS date_deleted timestamp DEFAULT null;
ALTER TABLE CUSTOMER ADD IF NOT EXISTS date_deleted timestamp DEFAULT null;
ALTER TABLE PAYMENTMETHOD ADD IF NOT EXISTS date_deleted timestamp DEFAULT null;
ALTER TABLE POSCLIENT ADD IF NOT EXISTS date_deleted timestamp DEFAULT null;
ALTER TABLE MLUSER ADD IF NOT EXISTS date_deleted timestamp DEFAULT null;

ALTER TABLE PRODUCT ADD IF NOT EXISTS visible_on_pos boolean DEFAULT TRUE;
ALTER TABLE CUSTOMER ADD IF NOT EXISTS visible_on_pos boolean DEFAULT TRUE;
ALTER TABLE PAYMENTMETHOD ADD IF NOT EXISTS visible_on_pos boolean DEFAULT TRUE;
ALTER TABLE POSCLIENT ADD IF NOT EXISTS visible_on_pos boolean DEFAULT TRUE;
ALTER TABLE MLUSER ADD IF NOT EXISTS visible_on_pos boolean DEFAULT TRUE;