ALTER TABLE POSCLIENT ADD IF NOT EXISTS logincode varchar(64) NOT NULL DEFAULT '';

ALTER TABLE POSCLIENT DROP CONSTRAINT IF EXISTS C_POSCLIENT_UNIQUE_LOGINCODE;
ALTER TABLE POSCLIENT ADD CONSTRAINT C_POSCLIENT_UNIQUE_LOGINCODE UNIQUE(logincode);