name: Pretty and lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Navigate to directory
        run: cd ${{ github.workspace }}/MLPos.Web/PosClient

      - name: Install dependencies
        run: npm install
      
      - name: Run pretty check
        run: npm run check

      - name: Run linter
        run: npm run lint