name: Validate TS build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ${{ github.workspace }}/MLPos.Web/PosClient

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install
      
      - name: Run Build
        run: npm run build